#!/bin/bash

if [[ "$(uname)" = "Darwin" ]]; then
  # GNU coreutils
  (type gcp >/dev/null 2>&1) && alias cp="gcp -i"
  (type gdate >/dev/null 2>&1) && alias date="gdate"
  (type gdu >/dev/null 2>&1) && alias du="gdu"
  (type ghead >/dev/null 2>&1) && alias head="ghead"
  (type gmkdir >/dev/null 2>&1) && alias mkdir="gmkdir"
  (type gmv >/dev/null 2>&1) && alias mv="gmv -i"
  (type grm >/dev/null 2>&1) && alias rm="grm -i"
  (type gtail >/dev/null 2>&1) && alias tail="gtail"
  (type gtee >/dev/null 2>&1) && alias tee="gtee"
  (type gtr >/dev/null 2>&1) && alias tr="gtr"
  # GNU findutils
  (type gfind >/dev/null 2>&1) && alias find="gfind"
  # GNU grep
  (type ggrep >/dev/null 2>&1) && alias grep="ggrep --color=auto"
  # GNU sed
  (type gsed >/dev/null 2>&1) && alias sed="gsed"

  alias showfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
  alias hidefiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
fi

alias reload='. $ZDOTDIR/.zshrc'

alias ~="cd ~"
alias ..="cd .."
alias path='tr : \\n <<< "$PATH"'
alias ea='$EDITOR -c cd\ %:h "$XDG_CONFIG_HOME/alacritty/alacritty.yml"'
alias en='$EDITOR -c cd\ %:h "$XDG_CONFIG_HOME/nvim/init.lua"'
alias et='$EDITOR -c cd\ %:h "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias ez='$EDITOR -c cd\ %:h "$ZDOTDIR/.zshrc"'

alias ip4="dig +short @resolver1.opendns.com myip.opendns.com | tee >(pbcopy)"
alias localip="ipconfig getifaddr en0 | tee >(pbcopy)"

(type bat >/dev/null 2>&1) && alias cat="bat -pp"

if type eza >/dev/null 2>&1; then
  alias ls="eza -G --icons --color auto -a -s type"
  alias ll="eza -l --icons --color auto -a -s type"
fi
