vim.g.mapleader = ","
vim.g.netrw_altv = 1
vim.g.netrw_banner = 1
vim.g.netrw_browse_split = 0
vim.g.netrw_preview = 1
vim.g.netrw_winsize = 25
vim.g.loaded_getscript = 1
vim.g.loaded_getscriptPlugin = 1
vim.g.loaded_vimball = 1
vim.g.loaded_vimballPlugin = 1

vim.opt.autoindent = true
vim.opt.background = "dark"
vim.opt.backup = false
vim.opt.belloff = "all"
vim.opt.breakindent = true
vim.opt.clipboard:append({ "unnamedplus" })
vim.opt.cmdheight = 1
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.hlsearch = true
vim.opt.inccommand = "split"
vim.opt.incsearch = true
vim.opt.joinspaces = false
vim.opt.list = true
vim.opt.listchars:prepend("trail:·")
vim.opt.listchars:prepend("tab:» ")
vim.opt.mouse = "n"
vim.opt.number = true
vim.opt.pumblend = 10
vim.opt.relativenumber = true
vim.opt.scrolloff = 8
vim.opt.shiftwidth = 4
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.showmode = false
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.undodir = vim.fn.stdpath("state")
vim.opt.updatetime = 200
vim.opt.wildoptions = "pum"
vim.opt.wrap = true
