#!/bin/bash

readonly BRANCHES=(
  "main"
  "master"
  "development"
  "develop"
  "dev"
  "hotfix"
  "production"
  "prod"
  "release"
  "staging"
)

current=$(git rev-parse --abbrev-ref HEAD)

for branch in "${BRANCHES[@]}"; do
  if [[ "${branch}" == "${current}" ]]; then
    read -rp $'\e[33;1m'"You are about to push to the ${current} branch. Are you sure?"$'\e[0m [y/N] ' </dev/tty
    if [[ "${REPLY}" != [yY]* ]]; then
      printf "Aborted.\n"
      exit 1
    fi
  fi
done
